name: beakerx
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - beakerx
  - traitlets
  - pip:
    - jupyterlab_launcher
    - ipywidgets
    - feedparser
    - paho-mqtt
    - jupyter_contrib_nbextensions
    - numpy
    - matplotlib
    - pandas