name: beakerx
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - beakerx
  - traitlets
  - ipython
  - vdom
  - jupyterlab_launcher
  - ipywidgets
  - beakerx
  - feedparser
  - paho-mqtt
  - jupyter_contrib_nbextensions
  - numpy
  - matplotlib
  - pandas