#!/bin/bash

beakerx install

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable python-markdown/main


jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install beakerx-jupyterlab

#jupyter labextension install @jupyterlab/geojson-extension jupyterlab-drawio
#jupyter lab clean
#jupyter lab build
mosquitto &